spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/practice;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    schema: classpath:h2/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console